name: Python application

on:
  push:
    branches: [ "master", "1.10", "1.9", "dev_1.10", "dev_1.9"]
  pull_request:
    branches: [ "master", "1.10", "1.9", "dev_1.10", "dev_1.9"]

permissions:
  contents: read

jobs:
  flake8-test:
    runs-on: ubuntu-latest
    container: python:3.11
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install -r requirements/test.txt
      - name: Check code formatting with flake8
        run: flake8 ./

  black-test:
    runs-on: ubuntu-latest
    container: python:3.11
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install black
      - name: Check code formatting with black
        run: black ./ --check --verbose --diff
